package temp;

public class RetrieveLink {

	public static void main(String[] args) {
		
		String emailBody = "<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n"
				+ "<head>\r\n"
				+ "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\r\n"
				+ "    <style type=\"text/css\">\r\n"
				+ "        body {\r\n"
				+ "            margin:0;\r\n"
				+ "            color:#333;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        a {\r\n"
				+ "            text-decoration:none;\r\n"
				+ "            color:#006699;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        p {\r\n"
				+ "            margin:0px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        img {\r\n"
				+ "            border:0;\r\n"
				+ "            margin:0;\r\n"
				+ "            text-align: center;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        #title p{\r\n"
				+ "            font-size:15px;\r\n"
				+ "            font-family: \"Amazon Ember\", Arial, sans-serif;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "    </style>\r\n"
				+ "    <title></title>\r\n"
				+ "</head>\r\n"
				+ "<body><img width=\"1\" height=\"1\" src=\"https://www.amazon.in/gp/r.html?C=DR9AEQ3CUVGD&K=2CDKWEBSST6U7&M=urn:rtn:msg:202410240841156ab2c05ce9734341b813c121e4f0p0eu&R=RN7YQH9YKXHB&T=O&U=https%3A%2F%2Fimages-eu.ssl-images-amazon.com%2Fimages%2FG%2F01%2Fnav%2Ftransp.gif&H=ISDEA10HQPCDS65LOFUKIMPL6QIA&ref_=pe_33270321_610684451_opens\" />\r\n"
				+ "<table align=\"center\" cellspacing=\"0\" width=\"520\" cellpadding=\"0\" style=\"padding-bottom: 20px;\">\r\n"
				+ "    <tbody>\r\n"
				+ "        <tr>\r\n"
				+ "            <td>\r\n"
				+ "                <table cellspacing=\"0\" width=\"520\" cellpadding=\"0\" style=\"margin-top:0px; margin-bottom: 0px; margin-left: 20px; margin-right: 20px;\">\r\n"
				+ "                    <tbody>\r\n"
				+ "                    <tr width=\"520\">\r\n"
				+ "                        <td width=\"520\" height=\"52\" style=\"border-bottom:1px solid #eaeaea; padding-top:10px;\">\r\n"
				+ "                            <table>\r\n"
				+ "                                <tr width=\"520\">\r\n"
				+ "                                    <td width=\"107\" id=\"logo\">\r\n"
				+ "                                        <img id=\"amazonLogoImg\" alt=\"Logo Image\" width=\"107\" height=\"auto\" src=\"https://m.media-amazon.com/images/G/01/authportal/tiv/amazon_logo_RGB._CB424887820_.png\"/>\r\n"
				+ "                                    </td>\r\n"
				+ "                                </tr>\r\n"
				+ "                            </table>\r\n"
				+ "                        </td>\r\n"
				+ "                    </tr>\r\n"
				+ "                        <tr>\r\n"
				+ "                            <td colspan=\"2\" align=\"left\" style=\"text-align: left; font-size:17px; font-family: 'Amazon Ember', Arial, sans-serif; padding-top: 15px; padding-bottom: 0px; padding-left: 0px; padding-right: 1px;\">\r\n"
				+ "                                <p>Arun,</p>\r\n"
				+ "                            </td>\r\n"
				+ "                        </tr>\r\n"
				+ "                    <tr>\r\n"
				+ "                        <td colspan=\"2\" align=\"left\" style=\"text-align: left; font-size:17px; font-family: 'Amazon Ember', Arial, sans-serif; padding-top: 15px; padding-bottom: 10px; padding-left: 0px; padding-right: 1px;\">\r\n"
				+ "                            <p>Someone is attempting to reset the password of your account.</p>\r\n"
				+ "                        </td>\r\n"
				+ "                    </tr>\r\n"
				+ "\r\n"
				+ "                    <tr>\r\n"
				+ "                        <td align=\"left\">\r\n"
				+ "                            <table align=\"left\" cellspacing=\"0\" cellpadding=\"0\" style=\"font-size:17px;\">\r\n"
				+ "                                <tr>\r\n"
				+ "                                    <td style=\"vertical-align: top; font-family: 'Amazon Ember', Arial, sans-serif; text-align: left; padding-top: 10px; padding-left: 0px; padding-right: 5px;\" >\r\n"
				+ "                                        When:\r\n"
				+ "                                    </td>\r\n"
				+ "                                    <td style=\"vertical-align: top; font-family: 'Amazon Ember', Arial, sans-serif; text-align: left; padding-top: 10px; padding-left: 0px; padding-right: 1px;\">\r\n"
				+ "                                        Oct 24, 2024 02:11 PM India Standard Time\r\n"
				+ "                                    </td>\r\n"
				+ "                                </tr>\r\n"
				+ "                                <tr>\r\n"
				+ "                                    <td style=\"vertical-align: top; font-family: 'Amazon Ember', Arial, sans-serif; text-align: left; padding-left: 0px; padding-right: 5px;\">\r\n"
				+ "                                        Device:\r\n"
				+ "                                    </td>\r\n"
				+ "                                    <td style=\"vertical-align: top; font-family: 'Amazon Ember', Arial, sans-serif; text-align: left; padding-left: 0px; padding-right: 1px;\">\r\n"
				+ "                                        Google Chrome Windows (Desktop)\r\n"
				+ "                                    </td>\r\n"
				+ "                                </tr>\r\n"
				+ "                                <tr>\r\n"
				+ "                                    <td style=\"vertical-align: top; font-family: 'Amazon Ember', Arial, sans-serif; text-align: left; padding-left: 0px; padding-right: 5px;\">\r\n"
				+ "                                        Near:\r\n"
				+ "                                    </td >\r\n"
				+ "                                    <td style=\"vertical-align: top; font-family: 'Amazon Ember', Arial, sans-serif; text-align: left; padding-left: 0px; padding-bottom: 10px; padding-right: 1px;\">\r\n"
				+ "                                        Telangana, India\r\n"
				+ "                                    </td>\r\n"
				+ "                                </tr>\r\n"
				+ "                            </table>\r\n"
				+ "                        </td>\r\n"
				+ "                    </tr>\r\n"
				+ "                            <tr>\r\n"
				+ "                                <td colspan=\"2\" align=\"left\" style=\"text-align: left; font-size:17px; font-family: 'Amazon Ember', Arial, sans-serif; padding-top: 15px; padding-bottom: 10px; padding-left: 0px; padding-right: 1px;\">\r\n"
				+ "                                    <p>If this was you, your verification code is:</p>\r\n"
				+ "                                </td>\r\n"
				+ "                            </tr>\r\n"
				+ "                            <tr>\r\n"
				+ "                                <td colspan=\"2\" align=\"left\" style=\"background-color: #D3D3D3; text-align: left; font-size:20px; font-weight: bold; font-family: 'Amazon Ember', Arial, sans-serif; padding-top: 15px; padding-bottom: 10px; padding-left: 10px; padding-right: 1px; border-top-left-radius: 10px; border-top-right-radius: 10px; border-bottom-left-radius: 10px; border-bottom-right-radius: 10px;\">\r\n"
				+ "                                    <p>  580274</p>\r\n"
				+ "                                </td>\r\n"
				+ "                            </tr>\r\n"
				+ "                            <tr>\r\n"
				+ "                                <td colspan=\"2\" align=\"left\" style=\"text-align: left; font-size:17px; font-family: 'Amazon Ember', Arial, sans-serif; padding-top: 15px; padding-bottom: 10px; padding-left: 0px; padding-right: 1px;\">\r\n"
				+ "                                    <p>If you didn&#39;t request it: <a href=\"https://www.amazon.in/gp/f.html?C=DR9AEQ3CUVGD&K=2CDKWEBSST6U7&M=urn:rtn:msg:202410240841156ab2c05ce9734341b813c121e4f0p0eu&R=EJLXA7CAF3AA&T=C&U=https%3A%2F%2Fwww.amazon.in%2Fa%2Fc%2Fr%2FrLtpMSBouKojTneOlpZxRvECZ%3Fref_%3Dpe_33270321_610684451&H=SMNXBLOTPSYTOFIBU9JUHBN04TOA&ref_=pe_33270321_610684451\"> click here to deny. </a></p>\r\n"
				+ "                                </td>\r\n"
				+ "                            </tr>\r\n"
				+ "                            <tr>\r\n"
				+ "                                <td width=\"520\" height=\"45\" colspan=\"2\" align=\"left\" style=\"font-size:17px; font-family: 'Amazon Ember', Arial, sans-serif; text-align: left; padding-left: 0px; padding-bottom: 10px; padding-top: 10px; padding-right: 1px;\">\r\n"
				+ "                                    Don’t share it with others.\r\n"
				+ "                                </td>\r\n"
				+ "                            </tr>\r\n"
				+ "                    <tr>\r\n"
				+ "                        <td width=\"520\" style=\"font-family: 'Amazon Ember', Arial, sans-serif; text-align: left; padding-left: 0px; padding-bottom: 10px; padding-top: 10px; padding-right: 1px;\">\r\n"
				+ "                            <div style=\"width: 520px; border: 1px solid #808080; padding-top: 5px; padding-left: 10px; padding-right: 10px; padding-bottom: 20px; margin-top: 25px; margin-right: 0px; margin-left: 0px; margin-bottom: 8px; color: #444;\">\r\n"
				+ "                                <h2 style=\"font-weight: 700; font-size: 15px; padding-bottom: 10px;\">Is it safe to follow this link?</h2>\r\n"
				+ "                                <div>\r\n"
				+ "                                    <a style=\"font-size: 13px; color: black; pointer-events: none; cursor: default; text-decoration: none;\">\r\n"
				+ "                                        The link provided in this email starts with “https://www.amazon.in”. If you prefer, copy the following link and paste it into a browser to view.\r\n"
				+ "                                    </a>\r\n"
				+ "                                </div>\r\n"
				+ "                                <br>\r\n"
				+ "                                <a style=\"font-size: 12px; color: black; pointer-events: none; cursor: default; text-decoration: none; font-weight: 600\">"
				+ "                                    https://www.amazon.in/a/c/r/rLtpMSBouKojTneOlpZxRvECZ\r\n"
				+ "                                </a>\r\n"
				+ "                            </div>\r\n"
				+ "                        </td>\r\n"
				+ "                    </tr>\r\n"
				+ "                    </tbody>\r\n"
				+ "                </table>\r\n"
				+ "            </td>\r\n"
				+ "        </tr>\r\n"
				+ "    </tbody>\r\n"
				+ "</table>\r\n"
				+ "<img width=\"1\" height=\"1\" src=\"https://www.amazon.in/gp/r.html?C=DR9AEQ3CUVGD&K=2CDKWEBSST6U7&M=urn:rtn:msg:202410240841156ab2c05ce9734341b813c121e4f0p0eu&R=ERUJ1FXXUYPG&T=E&U=https%3A%2F%2Fimages-eu.ssl-images-amazon.com%2Fimages%2FG%2F01%2Fnav%2Ftransp.gif&H=MEMCLQHAJDIUUKTWB153606DAACA&ref_=pe_33270321_610684451_open\" /></body>\r\n"
				+ "</html>";
		
		

	}

}
